import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home({ externalPostData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started
        </p>

        <div className={styles.grid}>
          <Link href="/pageone">
            <a className={styles.card}>
              <h2>Page 1 &rarr;</h2>
              <p>Anda akan menuju ke Page 1.</p>
            </a>
          </Link>

          <Link href="/pagetwo">
            <a className={styles.card}>
              <h2>Page 2 &rarr;</h2>
              <p>Anda akan menuju ke Page 2.</p>
            </a>
          </Link>
        </div>
      </main>

      <main>
        <p className={styles.description}>
          Data db.json
        </p>

        <div className={styles.grid}>
          {externalPostData.map((data) => {
            return (
              <Link href={data.link} key={data.id}>
                <a className={styles.card}>
                  <h3>{data.title}</h3>
                  <p>{data.excerpt}</p>
                </a>
              </Link>
            );
          })}


        </div>
      </main>

      <footer className={styles.footer}>
        Powered by Zikri Ramdani
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const apiURL = "http://localhost:3001/posts" | null;
  
  if(apiURL) {
    const response = await fetch(apiURL);
    const data = await response.json();
    return {
      props: {
        externalPostData: data,
      },
    };
  } else {
    const data = [
      {
        "id" : 1,
        "title": "Page 1",
        "excerpt": "Lorem Ipsum is simply dummy text of the printing and typesettingindustry.",
        "link": "/pageone"
      },
      {
        "id" : 2,
        "title": "Page 2",
        "excerpt": "Lorem Ipsum is simply dummy text of the printing and typesettingindustry.",
        "link": "/pagetwo"
      }
    ];
    return {
      props: {
        externalPostData: data,
      },
    };
  }
}