import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import Footer from '../components/footer';
import { useRouter } from 'next/router';

// add bootstrap css 
import 'bootstrap/dist/css/bootstrap.css';
import { signIn, signOut, useSession } from 'next-auth/client'

import React, { useState } from 'react';
import axios from 'axios';

export default function Home(props) {
    const username = useFormInput('');
    const password = useFormInput('');
    const [error, setError] = useState(null);
    const [loading, setLoading] = useState(false);
    const router = useRouter();
    
    // handle button click of login form
    const handleLogin = () => {
        setError(null);
        setLoading(true);
        axios.post(process.env.NEXT_PUBLIC_API_URL + 'users', { username: username.value, password: password.value }).then(response => {
            setLoading(false);
            console.log('res', response)
            // setUserSession(response.data.token, response.data.user);
            // router.push('/dashboard');
            
        }).catch(error => {
            setLoading(false);
        });
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Login - Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                <p className={styles.description}>
                Get started
                </p>

                <div className="w-100">
                    <form action="" method="POST">
                        <div className="mb-3">
                            <label className="form-label">Username</label>
                            <input type="text" name="username" className="form-control" required />
                        </div>
                        <div className="mb-3">
                            <label className="form-label">Password</label>
                            <input type="password" name="password" className="form-control" required />
                        </div>
                        <input className="btn btn-primary" type="button" value={loading ? 'Loading...' : 'Login'} onClick={handleLogin} disabled={loading} /><br></br>
                    </form>
                </div>

                <div className={styles.grid}>
                    <Link href="/register">
                        <a className={styles.card}>
                            <p>Belum punya akun? Daftar disini.</p>
                        </a>
                    </Link>
                </div>
            </main>

            <Footer></Footer>
        </div>
    )
}

const useFormInput = initialValue => {
    const [value, setValue] = useState(initialValue);
  
    const handleChange = e => {
        setValue(e.target.value);
    }
    return {
        value,
        onChange: handleChange
    }
}