import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from "next/link";

// add bootstrap css 
import 'bootstrap/dist/css/bootstrap.css';
import { signIn, signOut, useSession } from 'next-auth/client'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login - Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started
        </p>

        <div className="w-100">
          <form action="" method="POST">
            <div class="mb-3">
              <label for="exampleInputUsername1" class="form-label">Username</label>
              <input value="username 1" type="text" class="form-control" id="exampleInputUsername1" aria-describedby="usernameHelp" required />
            </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input value="password 1" type="password" class="form-control" id="exampleInputPassword1" required />
            </div>
            <button type="submit" class="btn btn-primary">Sign In</button>
          </form>
        </div>

        <div className={styles.grid}>
          <Link href="/register">
            <a className={styles.card}>
              <p>Belum punya akun? Daftar disini.</p>
            </a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        Powered by Zikri Ramdani
      </footer>
    </div>
  )
}